### ISSUE TITLE
How to edit the metadata and save it back as markdown?

### ISSUE THREAD

**Issue by jonathanmach** [rpearce/parse-md#14]
Hi!
Any suggestions on how to edit the metadata and save the changes back to the original markdown?

Thank you in advance!

**Comment by rpearce** [comment]
@jonathanmach I might be misunderstanding, but that's not something that this library would support. All this library does is parse the metadata and give it back to you in an object, as shown here: https://github.com/rpearce/parse-md#what-it-does

I'm going to close this as an issue, but feel free to ask more questions around it.
