### ISSUE TITLE
Can't use properly inside a node ESM package

### ISSUE THREAD

**Issue by alexghr** [rpearce/parse-md#24]
Hi,

Thanks for the great library! I'm having some trouble importing it in a project uses native node ESM.

Importing the default export seems to return an object with a `default` key inside of it. Here's an example:

```bash
$ cat test.mjs
import parseMD from "parse-md";
console.log(parseMD);
$ node test.mjs
{ default: [Function: parseMD] }
```

Directly calling `parseMD` (as per docs) at this point would obviously crash node because `parseMD` is an object, not a function.

Having looked at [package.json](https://github.com/rpearce/parse-md/blob/c6ae41a8cb73a0cf6d768d7c74be8755774844ea/package.json) I think it's using an older/deprecated way of specifying ESM exports. According to Node 16's docs we should use the `exports` key in `package.json` now: https://nodejs.org/api/packages.html#exports

I'm happy to contribute a fix to this if you're willing to publish a new version to npm for it 😄

**Comment by rpearce** [comment]
I wasn't even aware of that `exports` key! I will absolutely accept a PR, review it, try it out, merge it, publish it, and add you to the contributors list, if you're willing.

**Comment by rpearce** [comment]
I also need to convert this to TypeScript and upgrade all sorts of dev packages, so maybe I'll throw that in afterward, too.

**Comment by rpearce** [comment]
@alexghr This is released in v2.0.5

**Comment by rpearce** [comment]
@alexghr If you're feeling generous, could you also help me out by testing `v3.0.0`? I rewrote this in TypeScript.

**Comment by alexghr** [comment]
> @alexghr If you're feeling generous, could you also help me out by testing `v3.0.0`? I rewrote this in TypeScript.

hey dude, there are a couple of problems with v3.0.0

- `tsc` output files only have `.js` extension so `package.json` points at missing files now (e.g. `dist/cjs/index.cjs` doesn't exist, `dist/cjs/index.js` does though)
- its type information is not published. You'll need to set the `types` field in `package.json` https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by rpearce** [comment]
That's what I get for programming with a 15-month-old nearby. Thanks for looking at it.

I'll try to rectify this tonight and follow back up with you.

**Comment by rpearce** [comment]
@alexghr Can you try out `v3.0.1`? I just did this, and it seems to be working for me on node `v16.13.1`:

`package.json`:
```json
{
  "name": "testing",
  "version": "0.1.0",
  "main": "index.js",
  "type": "module",
  "dependencies": {
    "parse-md": "^3.0.1"
  }
}
```

`index.js`:
```js
import parseMD from "parse-md";
import fs from 'fs'

const fileContents = fs.readFileSync('first.md', 'utf8')
const { metadata, content } = parseMD(fileContents)

console.log({ metadata, content })
```

`first.md`:
```js
---
author: Foo
blah: Bar
---

# This is my post

Here's how I feel
```

```sh
$ node index.js
{
  metadata: { author: 'Foo', blah: 'Bar' },
  content: "\n# This is my post\n\nHere's how I feel\n"
}
```

**Comment by rpearce** [comment]
I'll keep this open until you're satisfied

**Comment by rpearce** [comment]
Another question: nodejs@14 has full support for ESModules, so is there any reason for me to keep outputting CommonJS?

I've been shooting from the hip a little on this, so please forgive me.

**Comment by alexghr** [comment]
😁 

`v3.0.1` works now, although I had to install `@types/js-yaml` in my project for it to compile with Typescript which is weird 🤔. I thought since I'm consuming the compiled `parse-md` code I shouldn't have to add its dependencies.



> Another question: nodejs@14 has full support for ESModules, so is there any reason for me to keep outputting CommonJS?

Well, now that you've marked the package as `type: "module"` CommonJS packages can't `require` it at all. I think this is fine as a "breaking change" for v3 and you could drop support for CJS completely 👍

**Comment by rpearce** [comment]
Well, this has been a disaster of a semver v3 release... it almost begs just skipping v3 and going to v4. Thank you for hanging in there with me.

I think this Typescript business in the types is because of https://github.com/rpearce/parse-md/blob/492986279015836f882700976d6ed6df95edb6e4/source/index.ts#L28, which is really just [`unknown`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ab1cf8125a365a3701c717e7305d51ae240ccde3/types/js-yaml/index.d.ts#L13). Could you share the steps/tooling you're doing on the Typescript side so I can do the same?

I'm going to put up a draft PR and see how you feel about it, since we're this far already.

I _really_ appreciate your time here.

**Comment by rpearce** [comment]
I'm out of time tonight, but I put up a draft: https://github.com/rpearce/parse-md/pull/31

**Comment by rpearce** [comment]
Alright, things should be ok in the latest release for usage with modules. I've updated the README to include a CommonJS note and to use `v2.x` for it.
