### ISSUE TITLE
Couple of v3.0.0 issues

### ISSUE THREAD

**Issue by rpearce** [rpearce/parse-md#29]
From https://github.com/rpearce/parse-md/issues/24#issuecomment-1004616608:

> * tsc output files only have .js extension so package.json points at missing files now (e.g. dist/cjs/index.cjs doesn't exist, dist/cjs/index.js does though)
> * its type information is not published. You'll need to set the types field in package.json https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by rpearce** [comment]
@alexghr Okay, you're 💯 about the `exports` pointing to the wrong file names (sorry about that), but if I'm reading this correctly, https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson, not including a `types` field will fall back to looking where main is?

**Comment by alexghr** [comment]
> not including a `types` field will fall back to looking where main is?

Yep, I think that's correct and from my testing of v3.0.1 it does find the type definitions.

**Comment by rpearce** [comment]
Closing to keep the conversation on the other issue
