### ISSUE TITLE
TypeError: parseMD is not a function

### ISSUE THREAD

**Issue by justinchan23** [rpearce/parse-md#9]
i tried to use the example listed in the readme and i get `TypeError: parseMD is not a function`

const fileContents = fs.readFileSync('posts/first.md', 'utf8')
const { metadata, content } = parseMD(fileContents)

console.log(metadata); // { title: 'Great first post', description: 'This is my first great post. Rawr' }
console.log(content); // "# My first post..."

**Comment by rpearce** [comment]
@justinchan23 I'll see if I can reproduce this tonight and get back with you. I have a sneaking suspicion it's from the recent build output updates.

**Comment by rpearce** [comment]
Update: I've reproduced this and will get a fix up ASAP.

**Comment by rpearce** [comment]
Oh... this should work for right now:
```js
const parseMD = require('parse-md').default
```
I'm still going to release a patch update, anyway, to update some things and see if I can fix this.

**Comment by rpearce** [comment]
After some reading, it seems that this is the way the node community has gone. There is a babel plugin for changing `exports.default` to `module.exports`, but that wasn't playing nicely with rollup, and this seems reasonable enough.

I've added you to the all contributors list for your contribution here as of this PR: https://github.com/rpearce/parse-md/pull/10
